spring:
  application:
    name: collect-task
  #配置MQ
  rabbitmq:
    host: 106.15.72.157 #内网IP 172.19.182.81
    port: 5672
    username: rabbitadmin
    password: FeiLei@123
    publisher-confirms: false

#热部署配置
devtools:
  livereload:
    enabled: true
  restart:
    enabled: true
    #additional-exclude: views/**


#配置日志
logging:
  #配置日志文件路径
  path: /temp/collect-task.log
  level:
    org.springfromework.web: warn
    org.hibernate: error
    com.tzj: warn
    com.tzj.collect.mapper: debug