spring:
  application:
    name: collect-task
  profiles:
    active: dynamicdb
  #配置MQ
  rabbitmq:
    host: 127.0.0.1 #内网IP 172.19.182.81
    port: 5672
    username: rabbitadmin
    password: FeiLei@123
    publisher-confirms: false
  redis:
    #open: false  # 是否开启redis缓存  true开启   false关闭
    #database: 0
    host: 127.0.0.1 #内网IP 172.19.182.81
    port: 6379
    password: FeiLei_!@#      # 密码（默认为空）
    timeout: 1000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接




#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tzj.collect.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #meta-object-handler: com.tzj.collect.common.handler.BaseMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


#热部署配置
devtools:
  livereload:
    enabled: true
  restart:
    enabled: true
    #additional-exclude: views/**


#配置日志
logging:
  #配置日志文件路径
  path: /temp/collect-task.log
  level:
    org.springfromework.web: warn
    org.hibernate: error
    com.tzj: info
    com.tzj.collect.mapper: debug