# Tomcat
server:
    tomcat:
    #    uri-encoding: UTF-8
        max-threads: 300
        max-connections: 1000
    #    min-spare-threads: 30
        accept-count: 300
    port: 9090
    connection-timeout: 20000
    #context-path: /collect
    jetty:
      acceptors: 2
      selectors: 4

# mysql
spring:
  servlet:
    multipart:
      max-request-size: 100MB
      enabled: true
      max-file-size: 100MB
      file-size-threshold: 0
  application:
    name: skin-battle
  # 环境 dev|pro || dynamicdb-test 测试多数据源配置 | dynamicdb-pro 正式多数据源配置
  profiles:
    #默认启动测试环境。可以启动应用的时候定当前环境 java -jar myproject.jar --spring.profiles.active = dynamicdb-pro
    active: dev
  # cache配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:config/ehcache.xml
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 发送邮件配置
  mail:
    host: smtp.163.com # 配置 smtp 服务器地址
    username: 18292835963@163.com # 配置邮箱用户名(你的邮箱地址)
    password: WXNQTDMOWPWPLNWB # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
        debug: true
    from: 18292835963@163.com


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.skin.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#热部署配置
devtools:
  livereload:
    enabled: true
  restart:
    enabled: true

#配置日志
logging:
  #配置日志文件路径
  path: /temp/skin-battle.log
  level:
    org.springfromework.web: warn
    org.hibernate: error


